<?php

require APPLIBS . DS . "RwsConstant.php";
require APPLIBS . DS . "Message.php";

/**
 * Test class for Message.
 * Generated by PHPUnit on 2015-03-25 at 11:11:13.
 */
class MessageTest extends CakeTestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers Message::getMessage
     * @todo Implement testGetMessage().
     */
    public function testGetMessage()
    {
        $params = array('replace_str_1', 'replace_str_2');
		$msg = Message::getMessage(RwsConstant::LANGUAGE_EN, 'TEST_ERR_MSG', $params);
		echo $msg;
    }
}
?>
